//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpgradeUntouchable.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpgradeUntouchable.Localization.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Force bridge.
        /// </summary>
        internal static string UU_BRIDGEMODE {
            get {
                return ResourceManager.GetString("UU_BRIDGEMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Can&apos;t upgrade to its own type!.
        /// </summary>
        internal static string UU_CANNOTUPGRADE_ITSELF {
            get {
                return ResourceManager.GetString("UU_CANNOTUPGRADE_ITSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use classic Touch This! mode
        ///&lt;color=yellow&gt;(WARNING: This may cause issues in the buildings!)&lt;/color&gt;.
        /// </summary>
        internal static string UU_CLASSICTOUCHTHISMODE {
            get {
                return ResourceManager.GetString("UU_CLASSICTOUCHTHISMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Currently upgrading to:.
        /// </summary>
        internal static string UU_CURRENTLYUPGRADINGTO {
            get {
                return ResourceManager.GetString("UU_CURRENTLYUPGRADINGTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Different kind of elevated network.
        /// </summary>
        internal static string UU_DIFFERENTELEVATIONTYPE {
            get {
                return ResourceManager.GetString("UU_DIFFERENTELEVATIONTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Different widths.
        /// </summary>
        internal static string UU_DIFFERENTHALFWIDTHS {
            get {
                return ResourceManager.GetString("UU_DIFFERENTHALFWIDTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Different stops placement support.
        /// </summary>
        internal static string UU_DIFFERENTHASSTOP {
            get {
                return ResourceManager.GetString("UU_DIFFERENTHASSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Different subservice.
        /// </summary>
        internal static string UU_DIFFERENTSUBSERVICE {
            get {
                return ResourceManager.GetString("UU_DIFFERENTSUBSERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Force elevated.
        /// </summary>
        internal static string UU_ELEVATEDMODE {
            get {
                return ResourceManager.GetString("UU_ELEVATEDMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bridge.
        /// </summary>
        internal static string UU_ELEVATIONTYPE__Bridge {
            get {
                return ResourceManager.GetString("UU_ELEVATIONTYPE__Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Default.
        /// </summary>
        internal static string UU_ELEVATIONTYPE__Default {
            get {
                return ResourceManager.GetString("UU_ELEVATIONTYPE__Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elevated.
        /// </summary>
        internal static string UU_ELEVATIONTYPE__Elevated {
            get {
                return ResourceManager.GetString("UU_ELEVATIONTYPE__Elevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ground.
        /// </summary>
        internal static string UU_ELEVATIONTYPE__Ground {
            get {
                return ResourceManager.GetString("UU_ELEVATIONTYPE__Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Undefined.
        /// </summary>
        internal static string UU_ELEVATIONTYPE__None {
            get {
                return ResourceManager.GetString("UU_ELEVATIONTYPE__None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Slope.
        /// </summary>
        internal static string UU_ELEVATIONTYPE__Slope {
            get {
                return ResourceManager.GetString("UU_ELEVATIONTYPE__Slope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tunnel.
        /// </summary>
        internal static string UU_ELEVATIONTYPE__Tunnel {
            get {
                return ResourceManager.GetString("UU_ELEVATIONTYPE__Tunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enable net picker window
        ///Allow to assign the net being built to be used here..
        /// </summary>
        internal static string uu_enableNetPickerWindow {
            get {
                return ResourceManager.GetString("uu_enableNetPickerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Force ground.
        /// </summary>
        internal static string UU_GROUNDMODE {
            get {
                return ResourceManager.GetString("UU_GROUNDMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Supports stop.
        /// </summary>
        internal static string UU_HASSTOP {
            get {
                return ResourceManager.GetString("UU_HASSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Net not supported!.
        /// </summary>
        internal static string UU_NETNOTSUPPORTED {
            get {
                return ResourceManager.GetString("UU_NETNOTSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;NONE SELECTED!&gt;.
        /// </summary>
        internal static string UU_NONESELECTED {
            get {
                return ResourceManager.GetString("UU_NONESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Try use the current segment elevation type.
        /// </summary>
        internal static string UU_NORMALMODE {
            get {
                return ResourceManager.GetString("UU_NORMALMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No stop support.
        /// </summary>
        internal static string UU_NOSTOP {
            get {
                return ResourceManager.GetString("UU_NOSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pick network from current selected.
        /// </summary>
        internal static string UU_PICKFROMCURRENTNETTOOLITEM {
            get {
                return ResourceManager.GetString("UU_PICKFROMCURRENTNETTOOLITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get this network to upgrade untouchable networks:
        ///&lt;color white&gt;{0}&lt;/color&gt;.
        /// </summary>
        internal static string UU_PICKNET_PATTERN {
            get {
                return ResourceManager.GetString("UU_PICKNET_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hold Control key to pick a road to use to upgrade untouchable segments.
        /// </summary>
        internal static string UU_PRESSCTRLTOPICK {
            get {
                return ResourceManager.GetString("UU_PRESSCTRLTOPICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tunnel mode.
        /// </summary>
        internal static string UU_SHOWUNDERGROUNDVIEW {
            get {
                return ResourceManager.GetString("UU_SHOWUNDERGROUNDVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TIP: Hold Control key to pick the hovered segment type in this mod!
        ///TIP: Use right click to invert an one-way/asymmetric segment direction.
        /// </summary>
        internal static string UU_TIP_PRESSCTRLTOPICK {
            get {
                return ResourceManager.GetString("UU_TIP_PRESSCTRLTOPICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Force tunnel.
        /// </summary>
        internal static string UU_TUNNELMODE {
            get {
                return ResourceManager.GetString("UU_TUNNELMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Upgrade this segment to:
        ///&lt;color white&gt;{0}&lt;/color&gt;.
        /// </summary>
        internal static string UU_UPGRADETO_PATTERN {
            get {
                return ResourceManager.GetString("UU_UPGRADETO_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use current net to upgrade untouchable.
        /// </summary>
        internal static string UU_USETHISNETWORKAUUT {
            get {
                return ResourceManager.GetString("UU_USETHISNETWORKAUUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The network you are about to upgrade in this place &lt;color yellow&gt;has no support to placing public transport stops&lt;/color&gt;, while the old one can.
        ///Check if you are not trying to use a non-station track in the place of the a station track. To pick a station track, you can both try to find it in Find It search or pick it from an existing building in the city while this mod tool is active and holding control while clicking in the desired track.
        ///
        ///If you know what you&apos;re doing, just go ahead.
        ///
        ///Continue the upgrad [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string UU_WOULDNTPLACESTOPSALERT_MESSAGE {
            get {
                return ResourceManager.GetString("UU_WOULDNTPLACESTOPSALERT_MESSAGE", resourceCulture);
            }
        }
    }
}
